version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm install --save-dev jest-junit
      - run:
          command: npm run test

workflows:
    build-and-test:
      jobs:
        - build-and-test